apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
