services:
  app:
    container_name: app
#    build: .
    image: ghcr.io/qwqw-333/pub_pyforum/app:0.0.1
    restart: unless-stopped
#    ports:
#      - 80:80
    env_file:
      - .env
    depends_on:
      - backend-db
    networks:
      - public
      - backend-private

  backend-db:
    container_name: backend-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - backend-private
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - public

volumes:
  db-data:

networks:
  public:
    name: public
  backend-private:
    name: backend-private