apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  PGADMIN_PASSWORD: TVROeTduZVJEcUFMOFlCdw==
  DJANGO_SUPERUSER_PASSWORD: N3puWVJhNFp6WXJ4dm1STg==
  EMAIL_HOST_PASSWORD: Z0hmUVBkVm5LM01TVDJLOA==
