apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: web
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: admin
