name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: forum
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and tests
      run: |
        python manage.py makemigrations authentication
        python manage.py migrate authentication
        python manage.py makemigrations profiles
        python manage.py migrate profiles
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
      env:
        CORS_ORIGIN_WHITELIST: ""
        SECRET_KEY: "+qne_u^_r3l^y9=vvfsvrbj+0%4e7&$iwm6hta2s+!b)r=1l!r"
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432

  deploy:
    needs: test
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker build and push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker build -t myapp .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push myapp
        
    - name: Deploy to server  
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '
          docker pull myapp
          docker stop myapp
          docker rm myapp
          docker run -d --name myapp myapp
        '
