name: Docker Compose Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/myapp:$(date +%s)
      
    - name: Docker Compose Build
      run: docker-compose build
      
    - name: Docker Compose Up
      run: |
        docker-compose up -d
        docker-compose ps
        
    - name: Test
      run: |
        docker-compose exec -T app python manage.py test
        
    - name: Docker Compose Down
      if: always()
      run: docker-compose down
